version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "Installing Helm..."
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export REPOSITORY_URI=$ECR_REPO_URL
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo "Building Docker image..."
      - docker build --no-cache -t frontend .
      - docker tag frontend:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Deploying with Helm..."
      - helm upgrade --install frontend ./helm/frontend --namespace frontend --set image.repository=$REPOSITORY_URI --set image.tag=$IMAGE_TAG
