version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:

  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - REPOSITORY_URI=$ECR_REPO_URL

      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo Build started on `date`

      - echo Building backend Docker image...
      - docker build -t backend .

      - docker tag backend:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo Deploying backend to EKS...

      - kubectl set image deployment/$K8S_DEPLOYMENT $K8S_CONTAINER=$REPOSITORY_URI:$IMAGE_TAG -n $K8S_NAMESPACE

      - kubectl rollout status deployment/$K8S_DEPLOYMENT -n $K8S_NAMESPACE

artifacts:
  files:
    - '**/*'
