replicaCount: 2

namespace: frontend

image:
  repository: 051912473169.dkr.ecr.ap-south-1.amazonaws.com/electronicastra/prod/frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

serviceAccount:
  create: false

httpRoute:
  enabled: false

ingress:
  enabled: true
  className: alb

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "250m"
    memory: "256Mi"
