replicaCount: 2

namespace: frontend

image:
  repository: 051912473169.dkr.ecr.ap-south-1.amazonaws.com/electronicastra/prod/frontend
  tag: ""
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

httpRoute:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: alb

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /

  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "250m"
    memory: "256Mi"

podAnnotations: {}

podLabels: {}

nodeSelector: {}

tolerations: []

affinity: {}
